apiVersion: apps/v1
kind: Deployment
metadata:
  name: gk-app-1
  labels:
    app: gk-app-1
  namespace: default
spec:
  selector:
    matchLabels:
      app: gk-app-1
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: gk-app-1
    spec:
      containers:
      - name: gk-app-1
        image: gk-app-1:0.0.2
        ports:
        - containerPort: 5000
          #   volumeMounts:
          #   - name: config-volume
          #     mountPath: /configs/
          # volumes:
          # - name: config-volume
          #   configMap:
          #     name: gk-app-1
